-- Active: 1690274640548@@127.0.0.1@3306@test
DROP TABLE IF EXISTS materials;

CREATE TABLE IF NOT EXISTS materials (
    id CHAR(36) NOT NULL PRIMARY KEY ,
    title VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
